// <auto-generated />
using System;
using Card_Creator.Classes.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Card_Creator.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20201029150738_CreateCard-Andreas")]
    partial class CreateCardAndreas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Card_Creator.Classes.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("typeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("typeID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Card_Creator.Classes.CardType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaknessID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WeaknessID");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("Card_Creator.Classes.Card", b =>
                {
                    b.HasOne("Card_Creator.Classes.CardType", "type")
                        .WithMany()
                        .HasForeignKey("typeID");
                });

            modelBuilder.Entity("Card_Creator.Classes.CardType", b =>
                {
                    b.HasOne("Card_Creator.Classes.CardType", "Weakness")
                        .WithMany()
                        .HasForeignKey("WeaknessID");
                });
#pragma warning restore 612, 618
        }
    }
}
